### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by UESHII** [UESHII/furima-28137#10]
## フリマアプリのURL
> https://furima-28137.herokuapp.com/
## Basic認証のIDとパスワード
> ID: admin
> Password: 2222
## 出品者用のメールアドレスとパスワード
> E-mail: test@example.com
> Password: test0000
## 購入者用のメールアドレスとパスワード
> E-mail: test2@example.com
> Password: test0000
## 購入用カードの番号・期限・セキュリティコード
> 番号: 4242424242424242
> 期限: 決済時より未来
> セキュリティーコード: 123

**Comment by techcamp-N** [comment]
上嶋さんご提出ありがとうございます！
挙動確認させて頂いたところ、以下の確認が出来ませんでしたので修正をお願いします！

・ログインしているユーザーだけが、出品ページへ遷移できる
（TestUser1と新しく登録したアカウント共に出品ボタンをクリックしても出来ませんでした）

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by UESHII** [comment]
@techcamp-N ご確認ありがとうございます。

自分の方で確認してみましたが、出品ページへの遷移はできているように見えます。
念の為ではありますが、今一度ご確認をお願い致します。
（自分がご指摘の意図を理解できていなければ、すみません。お手数ですがもう一度お知らせ下さい。）

宜しくお願い致します。
--
## TestUser1 新規投稿画面へ遷移
https://gyazo.com/d3620fb3fa354debf18ec63520d5bae9
## TestUser1 新規投稿 出品ボタン〜トップページ遷移
https://gyazo.com/895fc2ae3ac6458397a27889d5d9ba9b
## TestUser1 投稿一覧表示（投稿後）
https://gyazo.com/c5fa52cad7caa06199d3f036bd78c358
## TestUser2 新規投稿画面へ遷移
https://gyazo.com/a935627f4780327e4c7f439950d67795

**Comment by techcamp-N** [comment]
上嶋さんキャプチャ動画ありがとうございます！
そちらのボタンからですと、遷移できるのですね！こちらの確認不足で申し訳ありません。

右下のカメラマークの「出品する」というボタンから遷移出来なかったため、今回修正依頼を出させて頂きました。
カメラマークから出品できるようにして頂ければ、よりユーザーが使いやすいアプリになるかと思います。
ご対応頂けますでしょうか？

**Comment by UESHII** [comment]
@techcamp-N ご確認ありがとうございます。大変お手数をおかけしました。
修正しましたので再度ご確認を宜しくお願い致します。

**Comment by techcamp-N** [comment]
上嶋さん、迅速にご対応頂きありがとうございます！
カメラマーク「出品する」ボタンから出品ページに遷移し、出品自体もできることが確認出来ましたので
全てLGTMです、お疲れ様でした！^^
引き続き追加実装やオリアプの開発頑張っていきましょう！
